# Generated by Django 4.0.5 on 2022-06-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_style_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shirthome',
            name='price',
            field=models.IntegerField(),
        ),
    ]
