# Generated by Django 4.0.5 on 2022-06-07 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_style_app', '0005_overshirt_flannelshirt_dressshirt_cubanshirt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.CharField(max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=250)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main_style_app.category')),
            ],
        ),
        migrations.RemoveField(
            model_name='dressshirt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='flannelshirt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='overshirt',
            name='user',
        ),
        migrations.RemoveField(
            model_name='oxfordshirt',
            name='user',
        ),
        migrations.DeleteModel(
            name='CubanShirt',
        ),
        migrations.DeleteModel(
            name='DressShirt',
        ),
        migrations.DeleteModel(
            name='FlannelShirt',
        ),
        migrations.DeleteModel(
            name='OverShirt',
        ),
        migrations.DeleteModel(
            name='OxfordShirt',
        ),
    ]
