# Generated by Django 4.0.5 on 2022-06-08 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_style_app', '0006_category_products_remove_dressshirt_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shirt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main_style_app.products')),
            ],
        ),
    ]
