# Generated by Django 4.0.5 on 2022-06-08 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_style_app', '0007_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='shirt',
            new_name='product',
        ),
    ]
