# Generated by Django 4.0.5 on 2022-06-09 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_style_app', '0012_remove_review_cat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='created_at',
            new_name='date',
        ),
    ]
