# Generated by Django 4.0.5 on 2022-06-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_style_app', '0015_alter_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='Reviewers',
        ),
    ]
