# Generated by Django 4.0.5 on 2022-06-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_style_app', '0016_rename_user_review_reviewers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='Reviewers',
        ),
    ]
