# Generated by Django 4.0.5 on 2022-06-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_style_app', '0019_category_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideImg', models.CharField(max_length=250)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
